### ISSUE TITLE
No value for manufacturer

### ISSUE THREAD

**Issue by prechtelm** [jaredrummler/AndroidDeviceNames#35]
Hi,
we upgraded to 2.0.0. Following exception is thrown:

```
org.json.JSONException: No value for manufacturer
     at org.json.JSONObject.get(JSONObject.java:399)
     at org.json.JSONObject.getString(JSONObject.java:560)
     at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:374)
     at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:347)
     at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:186)
     at com.jaredrummler.android.device.DeviceName.getDeviceName(DeviceName.java:138)
```

**Comment by jeffreymuir** [comment]
Just upgraded to 2.0.0 and found that manufacturer is marked deprecated. Looked around in the code for any mention but did not find any yet. The hint is that we are not supposed to use it but then what are we supposed to use instead?

**Comment by jeffreymuir** [comment]
Found that it could have a null manufacturer with Google Pixel 3a. Looking at the code, it might be related to SharedPrefs from previous version. It caches using the shared preferences and might have an old entry. Noticed that it is saving the manufacturer when it looks it up in the database. Worked around it by using the Build.MANUFACTURER from Android.

**Comment by Climax777** [comment]
Kind of a blocker now. This library isn't usable currently

**Comment by arlm1** [comment]
I am getting this crash on a Moto G4 Plus with the 2.0.0 version

**Comment by ChrAnd2** [comment]
Same Error here with a Google Pixel 2

**Comment by Speedrockracer** [comment]
Same here on a Lenovo TB-8304F1

**Comment by shahramomidvar** [comment]
'manufacturer' is deprecated [
![Untitled](https://user-images.githubusercontent.com/39812683/101775571-eb636600-3b04-11eb-846e-1f40379df3fb.png)
](url)
manufacturer = info.manufacturer is null
