### ISSUE TITLE
ERROR: (1) no such table: devices

### ISSUE THREAD

**Issue by kelvin-dev** [jaredrummler/AndroidDeviceNames#63]
fyi
```(1) no such table: devices
2023-04-01 02:49:26.461 10515-10782 System.err              com.fujitsu.smartair.agent              W  android.database.sqlite.SQLiteException: no such table: devices (code 1): , while compiling: SELECT name, codename, model FROM devices WHERE codename LIKE ? OR model LIKE ?
2023-04-01 02:49:26.461 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
2023-04-01 02:49:26.461 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:896)
2023-04-01 02:49:26.461 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:507)
2023-04-01 02:49:26.461 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
2023-04-01 02:49:26.461 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
2023-04-01 02:49:26.461 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
2023-04-01 02:49:26.461 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
2023-04-01 02:49:26.462 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1346)
2023-04-01 02:49:26.462 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1193)
2023-04-01 02:49:26.462 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1064)
2023-04-01 02:49:26.462 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1232)
2023-04-01 02:49:26.462 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at com.jaredrummler.android.device.DeviceDatabase.queryToDevice(DeviceDatabase.java:116)
2023-04-01 02:49:26.462 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:193)
2023-04-01 02:49:26.462 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at com.jaredrummler.android.device.DeviceName$Request$GetDeviceRunnable.run(DeviceName.java:314)
2023-04-01 02:49:26.462 10515-10782 System.err              com.fujitsu.smartair.agent              W  	at java.lang.Thread.run(Thread.java:818)
```

**Comment by albertvaka** [comment]
I have the same problem. Before that I also get (probably related):
```
(11) database corruption at line 54055 of [9491ba7d73]
(11) statement aborts at 32: [CREATE TABLE IF NOT EXISTS android_metadata (locale TEXT)] database disk image is malformed
```
Is the database in a format that older Android devices don't understand? Is the minification breaking the database file? I have no clue on what's going on.
